import type { Metadata } from 'next';
import { Inter as FontSans, Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/providers';

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' });
const fontPlusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'], variable: '--font-plus-jakarta-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn('bg-background font-sans antialiased', fontSans.variable, fontPlusJakartaSans.variable)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem storageKey="greyy-blog-theme">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
